### ISSUE TITLE
Unable to Reorder sections

### ISSUE THREAD

**Issue by Giffen-good** [ferrlen/discussione#4]
To replicate:

1.  Click section toolbar
2.  Select "Move this item to a new section"
3.  Enter a new position

Observe error --> "Sorry! There was an error and this item couldn't be moved (error message: ' Internal Server Error '). Please check your internet connection and try again"

**Comment by ferrlen** [comment]
It's the same error from before, the line that was out of place, it's fixed now. Sorry for this!
